baseurl = "http://kitsu.github.io/"
languageCode = "en-us"
title = "Superfluous Comments"
theme = "hugo-theme-geppaku"
MetaDataFormat = "toml"
paginate = 10
disqusShortname = "SuperfComs"
googleAnalytics = "UA-77704589-1"
copyright = "© 2015 Ed Blake"

[blackfriday]
    smartypants = false

[author]
    # If you want to display author information set these
    # This is Optional values
    name = "Ed Blake"
    avatar = "images/avatar.jpeg"

    # Please set account ids
    # This is Optional values
    #twitter  = "your twitter id"
    linkedin = "edward-blake-b3601411b"
    github   = "kitsu"
    gplus = "118323029386640613972"
    stackoverflow = "770443"

[params]
    Desc = "Articles on programming topics written by someone who may not know what they are talking about."
    [params.sharebutton]
        # If you want to display share buttons set these
        # This is Optional values
        twitter  = false
        facebook = false
        # hatena   = true # hatena is Japanese social media
        google   = true
        pocket   = false
        # Please set id when you want to display facebook
        #facebookAppId = "your app id"

    [params.adsense]
        # If you want to display Google adsense set these
        # This is Optional values
        # 1. Create file written of the adsense tag into the directory "layouts/partials"
        # 2. Please set file path name omitted "layouts/partials"
        sidebar = "adsense/sidebar.html"
        content = "adsense/content.html"

[permalinks]
  post = "/:year/:month/:day/:filename/"
